# Generated by Django 6.0.1 on 2026-01-10 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='like',
            new_name='comments_count',
        ),
        migrations.RenameField(
            model_name='gallerymodel',
            old_name='Posted_on',
            new_name='posted_at',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('comment', models.TextField()),
                ('comment_likes', models.IntegerField(default=0)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.blogmodel')),
            ],
        ),
        migrations.CreateModel(
            name='CommentsLikeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=200)),
                ('liked_at', models.DateTimeField(auto_now_add=True)),
                ('liked_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.commenttable')),
            ],
            options={
                'unique_together': {('user_ip', 'liked_comment')},
            },
        ),
    ]
