# Generated by Django 6.0.1 on 2026-01-12 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_like_blogmodel_comments_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogmodel',
            name='comments_count',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='likes',
        ),
        migrations.DeleteModel(
            name='CommentsLikeTable',
        ),
    ]
